### ISSUE TITLE
Proposal to move development instructions to DEVELOPMENT.md

### ISSUE THREAD

**Issue by banesullivan** [girder/cookiecutter-girder-4#162]
In my opinion, the current contents of the `README.md` are purely development instructions and should go in a `DEVELOMPMENT.md` file. Then, the README should be adjusted to encourage downstream users to contribute more meaningful contents. 

Currently, in downstream projects generated from this cookiecutter, very few that I've seen have any sort of relevant information about the project in their READMEs. Considering these dev instructions are the same across all of the projects created from the cookiecutter, they should not be in the README as the README should be a project-specific overview and statement of need (in my opinion).

This new structure might encourage downstream developers to provide an overview of their project and any other relevant information in their README.

Here is a sample of what I think the new README could be (with a new `project_description` cookiecutter parameter):

```md
# {{ cookiecutter.project_name }}

{{ cookiecutter.project_description }}

## Development

Please see the development instructions in [DEVELOPMENT.md](./DEVELOPMENT.md).

## Connections

This Django project was generated from the [Girder 4 cookiecutter](https://github.com/girder/cookiecutter-girder-4).
```

**Comment by zachmullen** [comment]
Good idea. Feel free to make a PR of this.

**Comment by brianhelba** [comment]
I considered structuring things this way, but figured that without a substantive project description (which often takes time to solidify and may be too burdensome to ask for as part of the project creation), the `README.md` would end up being basically empty. In this circumstance, putting all the developer bootstrapping info into a `DEVELOPMENT.md` file makes it more difficult to immediately see, with no corresponding benefit (yes, there'd be a link to it from `README.md`, but people are lazy and can't be universally expected to click such things).

I expect larger projects to eventually grow the project-specific content of their `README.md` and perhaps make the decision to eventually move their development docs to a `DEVELOPMENT.md` (or a similar file).

However, now that more of the user community is familiar with the fact that development documentation is expected to exist, perhaps it's fine to put it into a different file by default, even if it makes it less immediately visible. I'd support a PR for this.

**Comment by banesullivan** [comment]
>  the fact that development documentation is expected to exist, perhaps it's fine to put it into a different file by default, even if it makes it less immediately visible

This is what I'm hoping will justify #168 

> often takes time to solidify and may be too burdensome to ask for as part of the project creation

Fair, but... making a decent project name requires just as much thought. If you know enough about what you're making to give it a name, then you know enough to provide a one-line description which later you can refine.

> I expect larger projects to eventually grow the project-specific content of their README.md

Let's make a habit of not waiting until your project is "large" to communicate what it does. Let's add a template README to encourage people to change it from the boilerplate.

**Comment by waxlamp** [comment]
> > often takes time to solidify and may be too burdensome to ask for as part of the project creation
> 
> Fair, but... making a decent project name requires just as much thought. If you know enough about what you're making to give it a name, then you know enough to provide a one-line description which later you can refine.
> 

💯 

> > I expect larger projects to eventually grow the project-specific content of their README.md
> 
> Let's make a habit of not waiting until your project is "large" to communicate what it does. Let's add a template README to encourage people to change it from the boilerplate.

💯 ✖️ 💯 

I want to support this idea by turning it around a bit: we already have a culture of not waiting to grow a project too large before we worry about things like adding testing/linting/typechecking, having good software design from the start, etc. I want to figure out how we can add "communicating about the project" to the list of things we don't defer indefinitely (or even for a moderate length of time) as a matter of our developer culture.

**Comment by brianhelba** [comment]
I think we need to clarify what the term "project" means here. I see at least two distinct meanings:
* a software project - any code in a repository
* a Django project - the source code for deploying a particular web application

Many open-source software projects are designed to be reusable; the most obvious case is a library. In such cases, the largest audience is probably downstream (potential) developer-users, who may want to know "what is the purpose of this library?", "what are the benefits of using it?", "how do I install it?", etc. Here, I agree that the focus of the README should be towards answering such questions, often with a marketing mindset. Such libraries are typically maintained by a much smaller group of internal developers, so while documenting the process for doing further development on the library itself is very important, it doesn't need to be extremely prominent.

However, a Django project is not designed to be reusable by anyone. It is highly specific to a particular instance (in sophisticated cases, perhaps a set of almost-identical instances). Marketing or providing a _raison d'être_ is not part of what a Django project's source code needs to do; that's the job of the web site itself (in a Home or About page). The most important audience for a Django project is the developers of that project. A good README here should explain how to execute and maintain the software.

We should not expect or optimize for the use case of random people looking to try out a Django project by running it locally in development mode. If people are interested in the application, they should visit the deployed site, not its source code. A marketing-savvy project will ensure that there's adequate content to explain and perhaps demo the functionality. Other projects may intentionally be designed as a walled garden, which are not looking to attract arbitrary new users.

---

However, I really do like the themes of #168, and I think we should apply them to other Girder 4-ecosystem **libraries**. I think there's a lot of opportunities for improvement, even for repos like https://github.com/girder/django-s3-file-field/ , which already have a substantive README.

**Comment by banesullivan** [comment]
I agree with your comparison of software projects (often libraries) and Django Projects and your thoughts with how we should optimize the README for the latter to point folks to the deployment/learn about the effort rather than any sort of re-usability. 

Perhaps an example would be what I have done in RD-WATCH: https://github.com/ResonantGeoData/RD-WATCH

I will update #168 accordingly

**Comment by waxlamp** [comment]
> However, a Django project is not designed to be reusable by anyone. It is highly specific to a particular instance (in sophisticated cases, perhaps a set of almost-identical instances). Marketing or providing a raison d'être is not part of what a Django project's source code needs to do; that's the job of the web site itself (in a Home or About page). The most important audience for a Django project is the developers of that project. A good README here should explain how to execute and maintain the software.

I don't think reusability is the only reason to have some introductory information in a front-facing README. Communicating the basic goal of a (Django) project in an environment like D&A is important for at least a couple of reasons:
- easing the onboarding of an engineer new to that project
- helping people who are otherwise unfamiliar with that project to learn what it's for (for purposes of, among other things, speaking intelligently about our capabilities/experience)

I think the objection that at project startup, the "elevator pitch" isn't known doesn't really apply--this is the case for many or most projects out there, and that in itself doesn't mean that such projects should *never* get around to communicating this basic info.

This is part of my thrust for more communication about our projects, even internally to each other. I think we should promote a culture of project leadership where a README may well begin empty (with just a link to DEVELOPMENT.md), but as part of the project execution, the team fills in some basic information in that file as, at the very least, a historical record.
